# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HikInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HikInterface(object):
    def setupUi(self, HikInterface):
        HikInterface.setObjectName("HikInterface")
        HikInterface.resize(400, 800)
        self.horizontalLayout = QtWidgets.QHBoxLayout(HikInterface)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.hikVerticalLayout_1 = QtWidgets.QVBoxLayout()
        self.hikVerticalLayout_1.setSpacing(10)
        self.hikVerticalLayout_1.setObjectName("hikVerticalLayout_1")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.hikVerticalLayout_1.addItem(spacerItem1)
        self.hikEnumButton = PrimaryPushButton(HikInterface)
        self.hikEnumButton.setMinimumSize(QtCore.QSize(200, 0))
        self.hikEnumButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.hikEnumButton.setObjectName("hikEnumButton")
        self.hikVerticalLayout_1.addWidget(self.hikEnumButton)
        self.hikEnumComboBox = ComboBox(HikInterface)
        self.hikEnumComboBox.setMinimumSize(QtCore.QSize(200, 0))
        self.hikEnumComboBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.hikEnumComboBox.setObjectName("hikEnumComboBox")
        self.hikVerticalLayout_1.addWidget(self.hikEnumComboBox)
        spacerItem2 = QtWidgets.QSpacerItem(20, 167, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.hikVerticalLayout_1.addItem(spacerItem2)
        self.hikOpenButton = TogglePushButton(HikInterface)
        self.hikOpenButton.setEnabled(False)
        self.hikOpenButton.setCheckable(True)
        self.hikOpenButton.setChecked(True)
        self.hikOpenButton.setObjectName("hikOpenButton")
        self.hikVerticalLayout_1.addWidget(self.hikOpenButton)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.hikVerticalLayout_1.addItem(spacerItem3)
        self.hikExposeLabel = BodyLabel(HikInterface)
        self.hikExposeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.hikExposeLabel.setObjectName("hikExposeLabel")
        self.hikVerticalLayout_1.addWidget(self.hikExposeLabel)
        self.hikExposeSlider = Slider(HikInterface)
        self.hikExposeSlider.setEnabled(False)
        self.hikExposeSlider.setMinimum(100)
        self.hikExposeSlider.setMaximum(30000)
        self.hikExposeSlider.setSingleStep(100)
        self.hikExposeSlider.setPageStep(100)
        self.hikExposeSlider.setProperty("value", 100)
        self.hikExposeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.hikExposeSlider.setObjectName("hikExposeSlider")
        self.hikVerticalLayout_1.addWidget(self.hikExposeSlider)
        self.hikGainLabel = BodyLabel(HikInterface)
        self.hikGainLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.hikGainLabel.setObjectName("hikGainLabel")
        self.hikVerticalLayout_1.addWidget(self.hikGainLabel)
        self.hikGainSlider = Slider(HikInterface)
        self.hikGainSlider.setEnabled(False)
        self.hikGainSlider.setMaximum(17)
        self.hikGainSlider.setSingleStep(1)
        self.hikGainSlider.setPageStep(1)
        self.hikGainSlider.setProperty("value", 0)
        self.hikGainSlider.setOrientation(QtCore.Qt.Horizontal)
        self.hikGainSlider.setObjectName("hikGainSlider")
        self.hikVerticalLayout_1.addWidget(self.hikGainSlider)
        self.hikFrameRateLabel = BodyLabel(HikInterface)
        self.hikFrameRateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.hikFrameRateLabel.setObjectName("hikFrameRateLabel")
        self.hikVerticalLayout_1.addWidget(self.hikFrameRateLabel)
        self.hikFrameRateSlider = Slider(HikInterface)
        self.hikFrameRateSlider.setEnabled(False)
        self.hikFrameRateSlider.setMinimum(10)
        self.hikFrameRateSlider.setMaximum(70)
        self.hikFrameRateSlider.setSingleStep(5)
        self.hikFrameRateSlider.setOrientation(QtCore.Qt.Horizontal)
        self.hikFrameRateSlider.setObjectName("hikFrameRateSlider")
        self.hikVerticalLayout_1.addWidget(self.hikFrameRateSlider)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.hikVerticalLayout_1.addItem(spacerItem4)
        self.horizontalLayout.addLayout(self.hikVerticalLayout_1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)

        self.retranslateUi(HikInterface)
        QtCore.QMetaObject.connectSlotsByName(HikInterface)

    def retranslateUi(self, HikInterface):
        _translate = QtCore.QCoreApplication.translate
        HikInterface.setWindowTitle(_translate("HikInterface", "Form"))
        self.hikEnumButton.setText(_translate("HikInterface", "枚举设备"))
        self.hikOpenButton.setText(_translate("HikInterface", "打开设备"))
        self.hikExposeLabel.setText(_translate("HikInterface", "曝光时间"))
        self.hikGainLabel.setText(_translate("HikInterface", "数字增益"))
        self.hikFrameRateLabel.setText(_translate("HikInterface", "相机帧率"))
from qfluentwidgets import BodyLabel, ComboBox, PrimaryPushButton, Slider, TogglePushButton
import resource_rc
