# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HikInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HikInterface(object):
    def setupUi(self, HikInterface):
        HikInterface.setObjectName("HikInterface")
        HikInterface.resize(400, 800)
        self.horizontalLayout = QtWidgets.QHBoxLayout(HikInterface)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.enum_dev = QtWidgets.QPushButton(HikInterface)
        self.enum_dev.setMinimumSize(QtCore.QSize(150, 0))
        self.enum_dev.setMaximumSize(QtCore.QSize(150, 16777215))
        self.enum_dev.setObjectName("enum_dev")
        self.verticalLayout.addWidget(self.enum_dev)
        self.open_hk = QtWidgets.QPushButton(HikInterface)
        self.open_hk.setObjectName("open_hk")
        self.verticalLayout.addWidget(self.open_hk)
        spacerItem2 = QtWidgets.QSpacerItem(20, 167, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.label = QtWidgets.QLabel(HikInterface)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.expose_time = QtWidgets.QSlider(HikInterface)
        self.expose_time.setEnabled(False)
        self.expose_time.setMinimum(100)
        self.expose_time.setMaximum(30000)
        self.expose_time.setSingleStep(100)
        self.expose_time.setPageStep(100)
        self.expose_time.setProperty("value", 5000)
        self.expose_time.setOrientation(QtCore.Qt.Horizontal)
        self.expose_time.setObjectName("expose_time")
        self.verticalLayout.addWidget(self.expose_time)
        self.label_2 = QtWidgets.QLabel(HikInterface)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.gain_value = QtWidgets.QSlider(HikInterface)
        self.gain_value.setEnabled(False)
        self.gain_value.setMaximum(17)
        self.gain_value.setSingleStep(1)
        self.gain_value.setPageStep(1)
        self.gain_value.setProperty("value", 2)
        self.gain_value.setOrientation(QtCore.Qt.Horizontal)
        self.gain_value.setObjectName("gain_value")
        self.verticalLayout.addWidget(self.gain_value)
        self.label_3 = QtWidgets.QLabel(HikInterface)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.frame_rate = QtWidgets.QLineEdit(HikInterface)
        self.frame_rate.setEnabled(False)
        self.frame_rate.setObjectName("frame_rate")
        self.verticalLayout.addWidget(self.frame_rate)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.get_param = QtWidgets.QPushButton(HikInterface)
        self.get_param.setEnabled(False)
        self.get_param.setObjectName("get_param")
        self.verticalLayout.addWidget(self.get_param)
        self.set_param = QtWidgets.QPushButton(HikInterface)
        self.set_param.setEnabled(False)
        self.set_param.setObjectName("set_param")
        self.verticalLayout.addWidget(self.set_param)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)

        self.retranslateUi(HikInterface)
        QtCore.QMetaObject.connectSlotsByName(HikInterface)

    def retranslateUi(self, HikInterface):
        _translate = QtCore.QCoreApplication.translate
        HikInterface.setWindowTitle(_translate("HikInterface", "Form"))
        self.enum_dev.setText(_translate("HikInterface", "枚举设备"))
        self.open_hk.setText(_translate("HikInterface", "打开设备"))
        self.label.setText(_translate("HikInterface", "曝光时间"))
        self.label_2.setText(_translate("HikInterface", "数字增益"))
        self.label_3.setText(_translate("HikInterface", "相机帧率"))
        self.get_param.setText(_translate("HikInterface", "获取参数"))
        self.set_param.setText(_translate("HikInterface", "设置参数"))
import resource_rc
