# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StoreInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StoreInterface(object):
    def setupUi(self, StoreInterface):
        StoreInterface.setObjectName("StoreInterface")
        StoreInterface.resize(388, 800)
        self.horizontalLayout = QtWidgets.QHBoxLayout(StoreInterface)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.storeVerticalLayout_1 = QtWidgets.QVBoxLayout()
        self.storeVerticalLayout_1.setSpacing(10)
        self.storeVerticalLayout_1.setObjectName("storeVerticalLayout_1")
        self.storeLabel = BodyLabel(StoreInterface)
        self.storeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.storeLabel.setObjectName("storeLabel")
        self.storeVerticalLayout_1.addWidget(self.storeLabel)
        self.storeVerticalLayout_2 = QtWidgets.QVBoxLayout()
        self.storeVerticalLayout_2.setObjectName("storeVerticalLayout_2")
        self.storeVerticalLayout_1.addLayout(self.storeVerticalLayout_2)
        self.gridLayout_1 = QtWidgets.QGridLayout()
        self.gridLayout_1.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_1.setObjectName("gridLayout_1")
        self.storeRgbCheckBox_1 = CheckBox(StoreInterface)
        self.storeRgbCheckBox_1.setChecked(True)
        self.storeRgbCheckBox_1.setObjectName("storeRgbCheckBox_1")
        self.gridLayout_1.addWidget(self.storeRgbCheckBox_1, 0, 0, 1, 1)
        self.storeIrCheckBox_1 = CheckBox(StoreInterface)
        self.storeIrCheckBox_1.setChecked(True)
        self.storeIrCheckBox_1.setObjectName("storeIrCheckBox_1")
        self.gridLayout_1.addWidget(self.storeIrCheckBox_1, 0, 1, 1, 1)
        self.storeIrCheckBox_2 = CheckBox(StoreInterface)
        self.storeIrCheckBox_2.setChecked(True)
        self.storeIrCheckBox_2.setObjectName("storeIrCheckBox_2")
        self.gridLayout_1.addWidget(self.storeIrCheckBox_2, 1, 0, 1, 1)
        self.storeVerticalLayout_1.addLayout(self.gridLayout_1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.storeVerticalLayout_1.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.storeVerticalLayout_1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)

        self.retranslateUi(StoreInterface)
        QtCore.QMetaObject.connectSlotsByName(StoreInterface)

    def retranslateUi(self, StoreInterface):
        _translate = QtCore.QCoreApplication.translate
        StoreInterface.setWindowTitle(_translate("StoreInterface", "Form"))
        self.storeLabel.setText(_translate("StoreInterface", "保存选项"))
        self.storeRgbCheckBox_1.setText(_translate("StoreInterface", "可见光原始图像"))
        self.storeIrCheckBox_1.setText(_translate("StoreInterface", "红外原始图像"))
        self.storeIrCheckBox_2.setText(_translate("StoreInterface", "红外温度矩阵"))
from qfluentwidgets import BodyLabel, CheckBox
import resource_rc
